CREATE TABLE CLIENTE(
IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
NACIMIENTO DATE NOT NULL
);

CREATE TABLE SERVICIO(
IDSERVICIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TIPOSERVICIO VARCHAR(50) NOT NULL
);

CREATE TABLE CLIENTESERVICOS(
IDCLIENTESERVICIOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
IDSERVICIO INT NOT NULL,
FOREIGN KEY(IDSERVICIO) REFERENCES SERVICIO(IDSERVICIO),
IDCLIENTE INT NOT NULL,
FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
UBICACION  VARCHAR(50) NOT NULL,
DESTINO  VARCHAR(50) NOT NULL,
COSTO  VARCHAR(50) NOT NULL,
HORA  TIME NOT NULL
);

CREATE TABLE CARACTERISTICA(
IDCARACTERISTICA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
DESCRIPCION VARCHAR(50) NOT NULL,
IDSERVICIO INT NOT NULL,
FOREIGN KEY(IDSERVICIO) REFERENCES SERVICIO(IDSERVICIO)
);

CREATE TABLE PROPIETARIO(
IDPROPIETARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICULO(
IDVEHICULO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
RIPOVEHICULO VARCHAR(50) NOT NULL,
IDPROPIETARIO INT NOT NULL,
FOREIGN KEY(IDPROPIETARIO) REFERENCES PROPIETARIO(IDPROPIETARIO),
CAPACIDAD VARCHAR(50) NOT NULL,
IDSERVICIO INT NOT NULL,
FOREIGN KEY(IDSERVICIO) REFERENCES SERVICIO(IDSERVICIO)

);

ALTER TABLE VEHICULO
ADD COLUMN MODELO VARCHAR(50) NOT NULL;

ALTER TABLE VEHICULO
MODIFY RIPOVEHICULO CHAR NOT NULL;

ALTER TABLE VEHICULO
ADD CONSTRAINT IDPROPIETARIO INT FOREIGN KEY REFERENCES PROPIETARIO(IDPROPIETARIO);


